spring:
  datasource:
    url: jdbc:h2:./data/db
    driver-class-name: "org.h2.Driver"
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        globally_quoted_identifiers: true
server:
  port: 80
  error:
    include-message: always
table-games:
  session:
    session-cleanup-interval: PT1M
    session-duration: PT5M
  rest:
    sse-timeout: PT5M